spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRESQL_DYNAMIC_PORT:5432}/idempotency_test
    username: postgres
    password: postgres
    hikari:
      minimumIdle: 5
      maximumPoolSize: 10
      connection-timeout: 1000

logging.level.com.zaxxer.hikari.HikariConfig: DEBUG
logging.level.com.zaxxer.hikari: DEBUG

trace: true